flags: 
  resyn:
    resyn: true
packages:
  - '.'
resolver: lts-13.11
extra-deps:
  - z3-4.3.1
  - recursion-schemes-5.0.2
#  - limp-0.3.2.3
#  - limp-cbc-0.3.2.3
# extra-include-dirs:
#  - <z3-home>/src/api
# extra-lib-dirs:
#  - <z3-home>/build  
